name: Example workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate coverage report
      run: |
        yarn install && yarn test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        #file: ./coverage.xml
        #files: ./coverage1.xml,./coverage2.xml
        directory: ./test/coverage
        flags: unittests
        #env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./test/coverage/codecov_report.gz